//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int CorreoID { get; set; }
        public int ContactoID { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual Contacto_Usuario Contacto_Usuario { get; set; }
    }
}
