//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Administradores
    {
        public string codigoUsuario { get; set; }
        public string contrasena { get; set; }
        public int EstadoID { get; set; }
    
        public virtual Estado Estado { get; set; }
    }
}
